### ISSUE TITLE
Decide on i18n approach

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-spa#38]
As a Neatline developer, I want the specification and display of localized interface strings to follow a consistent approach familiar to the React/Redux ecosystem.

**Comment by jamiefolsom** [comment]
Check out: https://react.i18next.com/

**Comment by feralresearch** [comment]
I’m looking at using this, which appears to be more or less the standard i18 tool for react folks: https://www.npmjs.com/package/react-intl

The only other one I was seriously considering was React-Intl-Universal which is React-Intl plus a singleton and some helper methods to access outside of React universe, which is nice, except 1. I’m not sure we need it and 2. It’s not that hard to write a singleton (or even port to that lib if necessary).
Any thoughts?

PS "downloads" is a crap way of measuring how useful/common something is, but 18n react-intl has 150k weeklies vs i18n-next 48k. I don't have intensely strong feelings about this, but given the intent to graduate this to public maintenance it seems like a good idea to go with the most common solution.

**Comment by akstuhl** [comment]
@tezcatlipoca Looks good! I think your reasoning makes sense. Only other considerations I can think to add to the mix would be friendliness with redux and portability of existing Neatline 2.x locale files (example: https://github.com/performant-software/Neatline/blob/master/languages/fr.po)

**Comment by feralresearch** [comment]
Based on a chat with Andy: The existing internationalization effort is PHP specific, so no matter what we will need to port those internationalization files, although this effort shouldn't be too difficult. 

To the task at hand (deciding which lib to use) this might be an argument in favor of using React-Intl-Universal, since we may want to access the internationalization outside of the react universe. 

Based on this I will set up a couple of test instances we can poke at together, including i18next. I'd love some input from @jamiefolsom once he's back on the suggestion for that particular package, perhaps it has some features we think are useful.

**Comment by feralresearch** [comment]
Capturing further conversation: An argument in favor of i18next might be that future work includes native application development, in which case the support for react native might be nice. I suspect we're dangerously close to yak shaving here, since the goal is to have internationalization - once we cut and paste the PHP locale files into JSON we can consume them in any number of ways (and it's also likely that the porting effort from web to native will be extensive enough that which library we use for i18n is not the hard problem). Still I'm going to do a deep-dive on a couple of these and will report back to the group and we can decide with Zoe and Jamie.

**Comment by jamiefolsom** [comment]
Based on the above conversation, and @mkobayashi21's doc, which he shared with us all this afternoon, I am inclined to agree with you @tezcatlipoca, that react-intl looks like a good choice. If you would like to do a deep dive on that tomorrow, and confirm when we meet, that it feels right to you, or not, I will defer to your decision on it. 

We will need to answer the questions about a) how to convert the existing PHP-world translation files to usable data for React-world, and b) how translators will do their thing going forward.

**Comment by jamiefolsom** [comment]
We went with react-localization, based on team members' recommendations.
