### ISSUE TITLE
Streamline Save and/or Notifications

### ISSUE THREAD

**Issue by feralresearch** [performant-software/neatline-spa#60]
At the moment, we require two unsaved changes messages as there are two save operations (one for exhibit and one for records). To support the current setup, the message should change when the user switches contexts.

**Comment by feralresearch** [comment]
@jamiefolsom @akstuhl @ZoeLeBlanc As an alternative to this, we could streamline a single save operation that saves any unsaved records and the exhibit form all at once. I don't see any particular downside to this, but I'd like thoughts before we do it?

**Comment by jamiefolsom** [comment]
Seems to me that an important consideration, maybe the key one in this case, is user expectations. Can a user change an exhibit and persist it without persisting "dirty" record values (where the value in the UI control has been changed), and vice-versa? 

If not, then a "persist-all-at-once" strategy seems fine, as long as we can communicate that expectation clearly through the UI. But if there's an expectation that exhibit and record data (and individual records) can be saved independently, then persist-all-at-once probably causes confusion.

**Comment by ZoeLeBlanc** [comment]
This morning @tezcatlipoca and I discussed the save UI for the editor and I think the persist all strategy is best one since it avoids people toggling between exhibit and records, and losing their edits. In addition the banner about unsaved changes, I think we might want to have an alert pop up before someone navigates away from that view if there are unsaved changes. I can add issue to github for the feature though it isn't a top priority since the banner is already fairly obvious.

**Comment by jamiefolsom** [comment]
As discussed just now, @tezcatlipoca, let's tackle this and #59 in a single PR, rather than as part of a larger catch-all PR.
