### ISSUE TITLE
On a newly created Omeka Site, clicking the neatline link returns phpinfo()

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/neatline-spa#67]
## Expected Behavior
  We should see some welcome information, explaining how to begin building a neatline exhibit.

## Current Behavior
  We get a phpinfo page, with some anomalous styles for the Omeka admin UI

### Screenshot
![Screenshot 2018-07-23 12.23.59.png](https://images.zenhubusercontent.com/55c903e94f7a08fbb7f434a8/6745b58c-f3c1-48b2-aa86-3c4b61c50a0a)

### Steps to Reproduce
1. Create a new Site within Omeka S
2. Click the Neatline link under the new site.

### Background Information
  Omeka S built from the Omeka-S dockerfile: https://github.com/scholarslab/neatline-omeka-s-docker (as of this 7/23/2018)

**Comment by akstuhl** [comment]
The 'Neatline' link as it existed was a non-functional leftover from early development and was removed in https://github.com/performant-software/neatline-omeka-s/pull/35 (though that same point in the admin navigation might be a convenient place for a link to the site's Neatline view, or to a new introduction view). Since the docker image includes neatline-omeka-s as a submodule, it will need to be updated following PR merges.

**Comment by jamiefolsom** [comment]
@akstuhl ok, cool -- I suspected the issue might be in the docker image. I will open an issue there -- thanks!
